import numpy as np
dt=np.dtype('i4')
print(dt)
dt1=np.dtype(float)
print(dt1)
dt2=np.dtype(complex)
print(dt2)
d3=np.dtype(bool)
print(d3)
c=np.dtype(int)
print(c)
d=np.dtype('>i4')
print(d)
p=np.dtype([('age',np.int8)])
print(p)
